package frc.robot.subsystems;

public class Hat implements ISubsystem {
    @Override
    public void onLoop() {}
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat
        //hat

    @Override
    public void submitTelemetry() {
        // TODO Auto-generated method stub
    }

    @Override
    public void receiveOptions() {
        // TODO Auto-generated method stub
    }
}
